---
title: "Sébastien Lê"
output: 
  html_document:
    # includes:
    #    in_header: [g_analytics.html,header_pubs.html]
    css: front.css
---

This website was essentially built to share open educational resources, and apps that should help you analyzing your data.

# Contact

Sébastien Lê <br>
Associate Professor <br>

Statistics and Computer Science Department <br>
Univ Rennes, [l'Institut Agro Rennes-Angers](https://www.institut-agro-rennes-angers.fr), CNRS, IRMAR - UMR 6625, F-35000 Rennes, France

Phone: +33 (0)2 23 48 58 81 <br>
email: sebastien.le@agrocampus-ouest.fr 


# Short curriculum

_ Associate professor in applied mathematics at l'Institut Agro Rennes-Angers

_ Ph.D. in applied mathematics with distinction, Université Paris IX-Dauphine

_ Holder of a diploma from the Institut de Statistique de l’Université de Paris

_ Holder of a Kukkiwon 4<sup>th</sup> Dan Taekwondo B.B.


# Ten things you need to know about me

1. I'm a statistician by training, and I've been working on sensory and consumer data since 2000.

2. I'm one of the co-authors of the FactoMineR and SensoMineR packages. Both packages are worldwide used. The first one is dedicated to the exploratory analysis of multivariate data, the second one is dedicated to the analysis of sensory data.

3. I'm a consultant.

4. I wrote more than 40 papers, and I'm one of the co-authors of Analyzing sensory data with R (334 pages, Chapman & Hall/CRC, The R Series) and of Exploratory multivariate analysis by example using R (240 pages, Chapman & Hall/CRC, Computer science and data analysis series).

5. My students have won more than 10 Syntec trophies, a national French contest that rewards the best students' project in marketing and opinion research.

6. I have strong connections with Asia, and in particular with Vietnam and Korea.

7. I have introduced the R software in Vietnam in 2005.

8. My collaborators would say about me that I'm innovative, I'm curious, I don't give up.

9. I've been invited for talks or tutorials in many different conferences or seminars. I like to work with many different people from different fields (sensory, marketing, psychology,...) and many different countries.

10. I like to understand data from different points of view, from different types (quanti- tative, qualitative, textual, images, sounds, videos...), to build new protocols, to run experiments.
